Repository andrebaltieri/AgendaEventos, pull requests merged in 2021-06, with the labels that each got.

#77 Remove unnecessary content
  Controllers/WeatherForecastController.cs
  Models/readme.md
  Scripts/readme.md
  WeatherForecast.cs
Labels: enhancement

#100 Display the SQL queries performed by EF on Console
  Data/DbContext.cs
Labels: enhancement, new feature

#102 CRUD Events
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  Controllers/EventController.cs
  Models/Event.cs
Labels: new feature

#111 Persist dates in UTC format
  Controllers/EventController.cs
  Controllers/RoleController.cs
  Data/DbContext.cs
  Models/Entity.cs
Labels: enhancement

#114 Coding standards
  .gitattributes
  Controllers/CategoryController.cs
  Controllers/EventController.cs
  Controllers/RoleController.cs
  Controllers/UserController.cs
Labels: enhancement
